# Generated by Django 4.1.1 on 2022-10-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupraEventTable',
        ),
    ]
