# Generated by Django 4.1.1 on 2022-10-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchImages',
        ),
    ]
