# Generated by Django 4.1.1 on 2022-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupraEventTable',
            fields=[
                ('supraeventid', models.IntegerField(db_column='supraeventid', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(db_column='end_datetime')),
            ],
            options={
                'db_table': 'SupraEventTable',
                'managed': False,
            },
        ),
    ]
