# Generated by Django 4.1.1 on 2022-11-07 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0004_continent_country_county_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AlterField(
            model_name='continent',
            name='continent',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(db_column='continent', srid=4326),
        ),
    ]
