# Generated by Django 4.1.1 on 2022-11-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0005_remove_country_continent_alter_continent_continent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
        migrations.DeleteModel(
            name='PreUpload',
        ),
    ]
