# Generated by Django 4.1.1 on 2022-11-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0006_delete_multipleimage_delete_preupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.RemoveField(
            model_name='county',
            name='country',
        ),
        migrations.RemoveField(
            model_name='region',
            name='county',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
