# Generated by Django 4.1.1 on 2022-09-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0002_annotators_behavior_event_lifestage_location_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='countyi',
            new_name='county',
        ),
    ]
