# Generated by Django 4.1.1 on 2022-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0003_rename_countyi_location_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='supraeventid',
        ),
    ]
