# Generated by Django 4.1.1 on 2022-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0004_remove_event_supraeventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supraeventid',
            field=models.IntegerField(blank=True, db_column='supraEventID', null=True),
        ),
    ]
