# Generated by Django 4.1.1 on 2022-09-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0005_event_supraeventid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='ai',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='annotators',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='behavior',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='deployments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lifestage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='occurence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'managed': False},
        ),
    ]
