# Generated by Django 4.1.1 on 2022-09-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0006_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ai',
            table='AI',
        ),
    ]
