# Generated by Django 4.1.1 on 2022-09-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_site', '0002_supraeventtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ai',
        ),
        migrations.DeleteModel(
            name='Annotators',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Behavior',
        ),
        migrations.DeleteModel(
            name='Deployments',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='eventid',
        ),
        migrations.DeleteModel(
            name='Lifestage',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mediaid',
        ),
        migrations.RemoveField(
            model_name='occurence',
            name='eventid',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='SupraEventTable',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Taxon',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Occurence',
        ),
    ]
